enum MESSAGE_TYPE {
    LOCATION_UPDATE= 'LOCATION_UPDATE',   
    RIDER_RIDE_REQUEST = 'RIDER_RIDE_REQUEST',
    RIDE_REQUEST_REJECT = 'RIDE_REQUEST_REJECT',
    RIDE_REQUEST_ACCEPT = 'RIDE_REQUEST_ACCEPT',
    RIDE_STOP = 'RIDE_STOP',
    RIDE_REQUEST_ACCEPT_ACK = 'RIDE_REQUEST_ACCEPT_ACK',
    SUBSCRIBE_FOR_LOCATION_UPDATE = 'SUBSCRIBE_FOR_LOCATION_UPDATE',
    UNSUBSCRIBE_FOR_LOCATION_UPDATE = 'UNSUBSCRIBE_FOR_LOCATION_UPDATE',
    UNSUBSCRIBE_FOR_ALL_LOCATION_UPDATE = 'UNSUBSCRIBE_FOR_ALL_LOCATION_UPDATE',
}


enum CHANNEL {
    LOCATION = 'location'
}

enum COMPANION_PREFERENCE {
    ANY = "ANY",
    MALE = "MALE",
    FEMALE = "FEMALE"
}

const LOCATION_HASH = 'LOCATION_HASH'
const OTP_HASH = 'OTP_HASH'
const DEFAULT_IMAGE_URL = "https://navicprofileimage2.blob.core.windows.net/image/placeholder.png"

enum QUEUE {
    MESSAGE = 'MESSAGE'
}

const REQEST_TIMEOUT = 20000 // 20 sec 

export { MESSAGE_TYPE, CHANNEL, QUEUE, REQEST_TIMEOUT, LOCATION_HASH, OTP_HASH, COMPANION_PREFERENCE, DEFAULT_IMAGE_URL}
