enum MESSAGE_TYPE {
    LOCATION_UPDATE= 'LOCATION_UPDATE',   
    RIDER_REQUEST_RIDE = 'RIDER_REQUEST_RIDE',
    DRIVER_ACCEPT_RIDE = 'DRIVER_ACCEPT_RIDE',
    DRIVER_REJECT_RIDE = 'DRIVER_REJECT_RIDE',
    RIDER_SYNACK_RIDE = 'RIDER_SYNACK_RIDE'
}


enum CHANNEL {
    LOCATION = 'location'
}

const LOCATION_HASH = 'LOCATION_HASH'

enum QUEUE {
    MESSAGE = 'MESSAGE'
}

const REQEST_TIMEOUT = 20000 // 20 sec 

export { MESSAGE_TYPE, CHANNEL, QUEUE, REQEST_TIMEOUT, LOCATION_HASH}
